### ISSUE TITLE
整体进度

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/cg-scratch-zh#1]
| 章节 | 贡献者 | 进度 | 奖励 |
| --- | --- | --- | --- |
| [零、简介](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/04.md) | @sanxincao  | 完成 | 完成 |
| [一、常用概念](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/05.md) | @sanxincao | 完成  | 完成 |
| [二、基本光线追踪](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/07.md) | @sanxincao | 完成  | 完成  |
| [三、光线](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/08.md) | @sanxincao | 完成  | 完成 |
| [四、阴影和倒影](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/09.md) | @gitRebdolphin8820 | 完成 | 完成 |
| [五、扩展光线跟踪器](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/10.md) | @Alex19830624  | 完成 | 完成 |
| [六、直线](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/12.md) |  @Alex19830624 | 完成 | 完成 |
| [七、实心三角形](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/13.md) | @Alex19830624 | 完成 | 完成 |
| [八、阴影三角形](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/14.md) | @Alex19830624 | 完成 | 完成 |
| [九、透视投影](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/15.md) | @Alex19830624 | 完成 | 完成 |
| [十、描述和渲染场景](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/16.md) | @Alex19830624 | 完成 | 完成 |
| [十一、裁剪](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/17.md) | @gitRebdolphin8820 | 完成 | 完成 |
| [十二、隐藏表面移除](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/18.md) | @gitRebdolphin8820 | 完成 | 完成 |
| [十三、阴影](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/19.md) | @gitRebdolphin8820 | 完成 | 完成 |
| [十四、纹理](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/20.md) | @gitRebdolphin8820 | 完成 | 完成 |
| [十五、扩展光栅化器](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/21.md) | @gitRebdolphin8820 | 完成 | 完成 |
| [附录 A、线性代数](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/23.md) | @gitRebdolphin8820  | 完成 | 完成 |
| [后记](https://github.com/apachecn/cg-scratch-zh/blob/master/docs/24.md) | @gitRebdolphin8820 | 完成 | 完成 |

**Comment by gitRebdolphin8820** [comment]
二、基本光线追踪 & 三、光线 & 附录A、线性代数

**Comment by Alex19830624** [comment]
我来校对5-10章吧，阿姨

**Comment by gitRebdolphin8820** [comment]
好的。



---Original---
From: ***@***.***&gt;
Sent at: 2022年7月16日(Sat) PM4:08
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apachecn/cg-scratch-zh] 整体进度 (Issue #1)




 
我来校对5-10章吧，阿姨

**Comment by wizardforcel** [comment]
@gitRebdolphin8820 第三章已经校对完了，再挑个别的吧

**Comment by gitRebdolphin8820** [comment]
ok，大家翻太快了😂，我附录＋后记吧

（🛰liy***）

**Comment by wizardforcel** [comment]
> ok，大家翻太快了😂，我附录＋后记吧

@gitRebdolphin8820 第四章还认领嘛？

**Comment by gitRebdolphin8820** [comment]
认领，第四章已经对完了👌



---Original---
From: ***@***.***&gt;
Sent at: 2022年7月21日(Thu) AM10:38
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apachecn/cg-scratch-zh] 整体进度 (Issue #1)




  
ok，大家翻太快了😂，我附录＋后记吧
  
@gitRebdolphin8820 第四章还认领嘛？

**Comment by wizardforcel** [comment]
@gitRebdolphin8820 尽快提交吧

**Comment by gitRebdolphin8820** [comment]
@wizardforcel 好的，已经全部校对结束。

**Comment by gitRebdolphin8820** [comment]
十一到十五章已认领

**Comment by gitRebdolphin8820** [comment]
😂OK，我先附录＋后记吧，前面大家翻太快了😂



---Original---
From: ***@***.***&gt;
Sent at: 2022年7月18日(Mon) AM8:57
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apachecn/cg-scratch-zh] 整体进度 (Issue #1)




 
@gitRebdolphin8820 第三章已经校对完了，再挑个别的吧
